In [ ]:
import torch

               

In [ ]:
#Reduction
x = torch.arange(3, dtype=torch.float32)
print(x)
print(f"sum of tensor's element:  {x.sum()}")

A = torch.arange(45).reshape(5, 9)
print(A)
print(f"shape of A: {A.shape}")
# sum along the first axis (columns)
print(f"sum of columns: {A.sum(axis=0)}") 
# sum along the second axis (rows)
print(f"sum of rows: {A.sum(axis=1)}") 

tensor([0., 1., 2.])
sum of tensor's element:  3.0
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44]])
shape of A: torch.Size([5, 9])
sum of columns: tensor([ 90,  95, 100, 105, 110, 115, 120, 125, 130])
tensor([ 36, 117, 198, 279, 360])
